### ISSUE TITLE
Sample HelloWorld is crashing

### ISSUE THREAD

**Issue by jordan4ibanez** [amerkoleci/joltc#12]
Hello, I am trying to utilize this binding to bind to jolt from Fortran. I get to the portion of code where it's:
```fortran
! Create the actual rigidbody.
floor_id = JPH_BodyInterface_CreateAndAddBody(body_interface, floor_settings, JPH_Activation_DontActivate)
``` 
and it simply results in:
```
 inIdx < mSize
 ././src/physics/joltc/../Jolt/Core/Array.h
 line:          455
```

Maybe I am missing something from the sample? Here is the code: https://github.com/jordan4ibanez/boxland_3d_thing/blob/master/src/physics/world.f90

**Comment by amerkoleci** [comment]
Hi,
Sorry I've never used Fortan thus is impossible for me to fix and repro this.

Feel free to submit PR if something is missing
